### PR TITLE
Add proxy option to the setup method

### PR DESCRIPTION
**Pull request by potato20**

### CODE REVIEW

**Comment by Heartz66** [comment]
Steam is very slow last week. 

Function loadMyInventory returns ETIMEDOUT as error since last 2 weeks. I am running 2 bots on the same application requesting the inventory about every 2 minutes for every bot on average.

Proxy support should fix the null response at Steam I guess.

**Comment by potato20** [comment]
gooby pls @Alex7Kom

**Comment by Alex7Kom** [comment]
Earlier I decided to implement passing any options to request (see https://github.com/Alex7Kom/node-steam-tradeoffers/pull/268#issuecomment-220557236), so I went ahead and did it in https://github.com/Alex7Kom/node-steam-tradeoffers/commit/fee79637f2dd2618e591d8e8447d6ba6781f4f28.
Check the docs on how to use it: https://github.com/Alex7Kom/node-steam-tradeoffers#setupoptions

**Comment by potato20** [comment]
Thanks @Alex7Kom

**Pull request closed without merging**
