### PR TITLE
More informative error message 

### PR DESCRIPTION
**Pull request by Alex-Nabu**
More informative error message on getHoldDuration failed

### CODE REVIEW

**Comment by Alex-Nabu** [comment]
Wasn't broken there was something up with my steam account. Added so error can be more useful if present.

**Comment by Alex-Nabu** [comment]
@Alex7Kom do you think this could get a merge i reckon it would be very helpful debug info for developers

**Comment by andrewda** [comment]
:+1: I especially think it's important to have as much information as possible in debug messages.

**Comment by Alex7Kom** [comment]
Thank you! Landed in https://github.com/Alex7Kom/node-steam-tradeoffers/commit/69b4166b92c159754b126baa3184ce9948389bb4.

**Pull request closed without merging**
